In [96]:
import numpy as np
import pandas as pd

data = pd.read_csv('Suicide_Detection.csv')

data

,Unnamed: 0,text,class
0,2,Ex Wife Threatening SuicideRecently I left my ...,suicide
1,3,Am I weird I don't get affected by compliments...,non-suicide
2,4,Finally 2020 is almost over... So I can never ...,non-suicide
3,8,i need helpjust help me im crying so hard,suicide
4,9,"I‚Äôm so lostHello, my name is Adam (16) and I‚Äôv...",suicide
...,...,...,...
232069,348103,If you don't like rock then your not going to ...,non-suicide
232070,348106,You how you can tell i have so many friends an...,non-suicide
232071,348107,pee probably tastes like salty teaüòèüí¶‚ÄºÔ∏è can som...,non-suicide
232072,348108,The usual stuff you find hereI'm not posting t...,suicide
232073,348110,I still haven't beaten the first boss in Hollo...,non-suicide

**Remove stop words**

In [74]:
import text_hammer as th
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize 
nltk.download('stopwords')
nltk.download('punkt')
lists = stopwords.words('english')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\diana\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\diana\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [97]:
stopwords_list = set(stopwords.words('english'))

def remove_stopwords(text):
  tokens = word_tokenize(text)
  tokens_without_stopwords = [word for word in tokens if word.lower() not in stopwords_list]
  text_without_stopwords = " ".join(tokens_without_stopwords)
  return text_without_stopwords

data['text'] = data['text'].apply(remove_stopwords)
data.head()

   Unnamed: 0                                               text        class
0           2  Ex Wife Threatening SuicideRecently left wife ...      suicide
1           3  weird n't get affected compliments 's coming s...  non-suicide
2           4  Finally 2020 almost ... never hear `` 2020 bad...  non-suicide
3           8                  need helpjust help im crying hard      suicide
4           9  ‚Äô lostHello , name Adam ( 16 ) ‚Äô struggling ye...      suicide

**Preprocessing**

In [98]:
import re

def remove_emails(text):
    # Manual implementation to remove emails
    return re.sub(r'\S+@\S+', '', text)

def remove_html_tags(text):
    # Manual implementation to remove HTML tags
    return re.sub(r'<.*?>', '', text)

def remove_special_chars(text):
    # Manual implementation to remove special characters
    return re.sub(r'[^a-zA-Z0-9\s]', '', text)

def remove_accented_chars(text):
    # Manual implementation to remove accented characters
    # You can use unidecode or other methods for a more comprehensive solution
    return re.sub(r'[^\x00-\x7F]+', '', text)

def text_preprocessing(df, col_name):
    column = col_name
    df[column] = df[column].apply(lambda x: str(x).lower())
    df[column] = df[column].apply(lambda x: remove_emails(x))
    df[column] = df[column].apply(lambda x: remove_html_tags(x))
    df[column] = df[column].apply(lambda x: remove_special_chars(x))
    df[column] = df[column].apply(lambda x: remove_accented_chars(x))
    return df

data = text_preprocessing(data, 'text')
data.head()

   Unnamed: 0                                               text        class
0           2  ex wife threatening suiciderecently left wife ...      suicide
1           3  weird nt get affected compliments s coming som...  non-suicide
2           4  finally 2020 almost  never hear  2020 bad year...  non-suicide
3           8                  need helpjust help im crying hard      suicide
4           9   losthello  name adam  16   struggling years  ...      suicide

**Tokenizer**

In [113]:
data

,Unnamed: 0,text,class
0,2,ex wife threatening suiciderecently left wife ...,suicide
1,3,weird nt get affected compliments s coming som...,non-suicide
2,4,finally 2020 almost never hear 2020 bad year...,non-suicide
3,8,need helpjust help im crying hard,suicide
4,9,losthello name adam 16 struggling years ...,suicide
...,...,...,...
232069,348103,nt like rock going get anything go https musi...,non-suicide
232070,348106,tell many friends lonely everything deprived ...,non-suicide
232071,348107,pee probably tastes like salty tea someone dra...,non-suicide
232072,348108,usual stuff find herei m posting sympathy pity...,suicide
232073,348110,still nt beaten first boss hollow knight ve f...,non-suicide

In [110]:
data2 = data.copy()

data2

,Unnamed: 0,text,class
0,2,ex wife threatening suiciderecently left wife ...,suicide
1,3,weird nt get affected compliments s coming som...,non-suicide
2,4,finally 2020 almost never hear 2020 bad year...,non-suicide
3,8,need helpjust help im crying hard,suicide
4,9,losthello name adam 16 struggling years ...,suicide
...,...,...,...
232069,348103,nt like rock going get anything go https musi...,non-suicide
232070,348106,tell many friends lonely everything deprived ...,non-suicide
232071,348107,pee probably tastes like salty tea someone dra...,non-suicide
232072,348108,usual stuff find herei m posting sympathy pity...,suicide
232073,348110,still nt beaten first boss hollow knight ve f...,non-suicide

In [111]:
def custom_tokenizer(text):
    tokens = word_tokenize(text)
    return tokens

def tokenize_columns(df, text_column):
    df[text_column] = df[text_column].apply(lambda x: custom_tokenizer(str(x).lower()))
    return df

tokenize_data = tokenize_columns(data2, 'text')
print(tokenize_data[['text']])

tokenize_data.head()

                                                     text
0       [ex, wife, threatening, suiciderecently, left,...
1       [weird, nt, get, affected, compliments, s, com...
2       [finally, 2020, almost, never, hear, 2020, bad...
3                [need, helpjust, help, im, crying, hard]
4       [losthello, name, adam, 16, struggling, years,...
...                                                   ...
232069  [nt, like, rock, going, get, anything, go, htt...
232070  [tell, many, friends, lonely, everything, depr...
232071  [pee, probably, tastes, like, salty, tea, some...
232072  [usual, stuff, find, herei, m, posting, sympat...
232073  [still, nt, beaten, first, boss, hollow, knigh...

[232074 rows x 1 columns]

   Unnamed: 0                                               text        class
0           2  [ex, wife, threatening, suiciderecently, left,...      suicide
1           3  [weird, nt, get, affected, compliments, s, com...  non-suicide
2           4  [finally, 2020, almost, never, hear, 2020, bad...  non-suicide
3           8           [need, helpjust, help, im, crying, hard]      suicide
4           9  [losthello, name, adam, 16, struggling, years,...      suicide

In [118]:
tokenize_data2 = tokenize_data.copy()

tokenize_data2

,Unnamed: 0,text,class
0,2,"[ex, wife, threatening, suiciderecently, left,...",suicide
1,3,"[weird, nt, get, affected, compliments, s, com...",non-suicide
2,4,"[finally, 2020, almost, never, hear, 2020, bad...",non-suicide
3,8,"[need, helpjust, help, im, crying, hard]",suicide
4,9,"[losthello, name, adam, 16, struggling, years,...",suicide
...,...,...,...
232069,348103,"[nt, like, rock, going, get, anything, go, htt...",non-suicide
232070,348106,"[tell, many, friends, lonely, everything, depr...",non-suicide
232071,348107,"[pee, probably, tastes, like, salty, tea, some...",non-suicide
232072,348108,"[usual, stuff, find, herei, m, posting, sympat...",suicide
232073,348110,"[still, nt, beaten, first, boss, hollow, knigh...",non-suicide

In [117]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import ComplementNB

# Join the tokenized words into sentences (documents)
documents = tokenize_data2['text'].apply(lambda x: ' '.join(x))

documents

0         ex wife threatening suiciderecently left wife ...
1         weird nt get affected compliments s coming som...
2         finally 2020 almost never hear 2020 bad year e...
3                         need helpjust help im crying hard
4         losthello name adam 16 struggling years afraid...
                                ...
232069    nt like rock going get anything go https music...
232070    tell many friends lonely everything deprived p...
232071    pee probably tastes like salty tea someone dra...
232072    usual stuff find herei m posting sympathy pity...
232073    still nt beaten first boss hollow knight ve fo...
Name: text, Length: 232074, dtype: object

In [121]:

# Use CountVectorizer to convert the text data into a bag-of-words representation
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

# Map 'class' column to numeric values
y = data2['class'].map({'non-suicide': 0, 'suicide': 1})

In [122]:

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=19)

# Create and train the Complement Naive Bayes model
cnb = ComplementNB()
cnb.fit(X_train, y_train)

# Evaluate the model
train_accuracy = cnb.score(X_train, y_train)
test_accuracy = cnb.score(X_test, y_test)

print("Train accuracy: {:.2f}%".format(train_accuracy * 100))
print("Test accuracy: {:.2f}%".format(test_accuracy * 100))

Train accuracy: 90.81%
Test accuracy: 89.91%

In [124]:
import joblib
# Save the trained Complement Naive Bayes model
model_filename = 'complement_naive_bayes_model.joblib'
joblib.dump(cnb, model_filename)
print(f'Model saved to {model_filename}')

# Save the CountVectorizer
vectorizer_filename = 'count_vectorizer.joblib'
joblib.dump(vectorizer, vectorizer_filename)
print(f'CountVectorizer saved to {vectorizer_filename}')

Model saved to complement_naive_bayes_model.joblib
CountVectorizer saved to count_vectorizer.joblib

In [135]:
def custom_tokenizer(text):
    tokens = word_tokenize(text)
    return tokens

# Load the saved Complement Naive Bayes model
loaded_model = joblib.load('complement_naive_bayes_model.joblib')

# Load the saved CountVectorizer
loaded_vectorizer = joblib.load('count_vectorizer.joblib')
# Example new data
new_data = {
    'text': ['I really enjoyed the movie', 'This product is terrible', 'I want to kill my self', 'Im so happy today']
}

# Convert the new data to a DataFrame
new_df = pd.DataFrame(new_data)

# Preprocess the new data (assuming you have a text_preprocessing function)
new_df = text_preprocessing(new_df, 'text')

tokenized_new_data = pd.DataFrame(new_data)
tokenized_new_data['text'] = tokenized_new_data['text'].apply(lambda x: custom_tokenizer(str(x).lower()))

# Join the tokenized words into sentences (documents)
new_documents = tokenized_new_data['text'].apply(lambda x: ' '.join(x))

# Use the loaded vectorizer to convert the new text data into a bag-of-words representation
X_new = loaded_vectorizer.transform(new_documents)

# Predict the sentiment using the loaded Complement Naive Bayes model
predictions = loaded_model.predict(X_new)

# Map the numeric predictions back to class labels
predicted_classes = pd.Series(predictions).map({0: 'non-suicide', 1: 'suicide'})


# Add predictions to the DataFrame
new_df['predicted_class'] = predicted_classes

# Display the results
print(new_df[['text', 'predicted_class']])

                         text predicted_class
0  i really enjoyed the movie     non-suicide
1    this product is terrible     non-suicide
2      i want to kill my self         suicide
3           im so happy today     non-suicide

In [ ]:
# Load the saved Complement Naive Bayes model
loaded_model = joblib.load('complement_naive_bayes_model.joblib')

# Load the saved CountVectorizer
loaded_vectorizer = joblib.load('count_vectorizer.joblib')
# Example new data
new_data = ""

# Convert the new data to a DataFrame
new_df = pd.DataFrame(new_data)

# Preprocess the new data (assuming you have a text_preprocessing function)
new_df = text_preprocessing(new_df, 'text')

tokenized_new_data = pd.DataFrame(new_data)
tokenized_new_data['text'] = tokenized_new_data['text'].apply(lambda x: custom_tokenizer(str(x).lower()))

# Join the tokenized words into sentences (documents)
new_documents = tokenized_new_data['text'].apply(lambda x: ' '.join(x))

# Use the loaded vectorizer to convert the new text data into a bag-of-words representation
X_new = loaded_vectorizer.transform(new_documents)

# Predict the sentiment using the loaded Complement Naive Bayes model
predictions = loaded_model.predict(X_new)

# Map the numeric predictions back to class labels
predicted_classes = pd.Series(predictions).map({0: 'non-suicide', 1: 'suicide'})